# Generated by Django 3.1.4 on 2021-02-06 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('[A-Z]([A-Z]|[0-9]){2,3}')])),
                ('register_date', models.DateField()),
                ('is_fetched', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Metar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(validators=[django.core.validators.RegexValidator('\\A([A-Z]([A-Z]|[0-9]){2,3} [1-3])')])),
                ('station_id', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('[A-Z]([A-Z]|[0-9]){2,3}')])),
                ('observation_time', models.DateTimeField()),
                ('temp_c', models.FloatField(validators=[django.core.validators.MaxValueValidator(70), django.core.validators.MinValueValidator(-60)])),
                ('dewpoint_c', models.FloatField(validators=[django.core.validators.MaxValueValidator(70), django.core.validators.MinValueValidator(-60)])),
                ('wind_dir_degrees', models.PositiveSmallIntegerField(default=360, validators=[django.core.validators.MaxValueValidator(360)])),
                ('wind_speed_kt', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)])),
                ('wind_gust_kt', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150)])),
                ('visibility_m', models.PositiveSmallIntegerField(default=9999, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('altim_in_hg', models.FloatField(validators=[django.core.validators.MaxValueValidator(32.5), django.core.validators.MinValueValidator(25.1)])),
                ('wx_string', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('\\A[-\\+]?[A-Z]{2,10}')])),
                ('cloud_ceiling', models.PositiveIntegerField(blank=True, null=True)),
                ('vert_vis_ft', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metar_type', models.CharField(choices=[('METAR', 'METAR'), ('SPECI', 'SPECI')], default='METAR', max_length=5)),
            ],
        ),
        migrations.AddConstraint(
            model_name='metar',
            constraint=models.UniqueConstraint(fields=('station_id', 'observation_time'), name='unique_metar'),
        ),
    ]
