# Generated by Django 3.1.4 on 2021-01-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('station_id', models.CharField(max_length=4)),
                ('observation_time', models.DateTimeField()),
                ('temp_c', models.FloatField()),
                ('dewpoint_c', models.FloatField()),
                ('wind_dir_degrees', models.PositiveSmallIntegerField()),
                ('wind_speed_kt', models.PositiveSmallIntegerField()),
                ('wind_gust_kt', models.PositiveSmallIntegerField()),
                ('visibility_m', models.PositiveSmallIntegerField()),
                ('altim_in_hg', models.FloatField()),
                ('wx_string', models.CharField(max_length=12)),
                ('cloud_ceiling', models.PositiveIntegerField()),
                ('metar_type', models.CharField(max_length=5)),
            ],
        ),
    ]
